apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-hello-world
spec:
  replicas: 3
  template:
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - topologyKey: kubernetes.io/hostname
      #      labelSelector:
      #        matchLabels:
      #          app: kubernetes-hello-world
      containers:
      - name: kubernetes-hello-world
        resources:
          limits:
            cpu: 600m
            memory: 2Gi
          requests:
            cpu: 600m
            memory: 2Gi
